name: Deploy SubMap

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    env:
      DEPLOYMENT_DIR: /etc/nginx/html/transmap
    
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: build files
      run: npm run build

    - name: Copy files to NGINX
      run: |
        rm -r  $DEPLOYMENT_DIR || true
        mkdir -p $DEPLOYMENT_DIR
        cp -r dist/* $DEPLOYMENT_DIR
        sudo systemctl reload nginx